### import libraries

In [1]:
import pandas as pd
from datetime import datetime

### Function to handle coordinates

In [2]:
def lat_lon_to_float(v):
    if (v[-1] == "S") or (v[-1] == "W"):
        multiplier = -1
    else :
        multiplier = 1
    return float(v[:-1]) * multiplier

### Data extraction

In [3]:
data = []

with open("../Data/hurdat2-1851-2021-100522.txt", "r") as f:
    for line in f.readlines():
        if line.startswith("AL"):
            storm_id = line.split(",")
            storm_number = storm_id[0].strip()
            Name = storm_id[1].strip()
        else:
            location_line = line.split(",")
            Date = location_line[0].strip()
            Time = location_line[1].strip()
            Date_Time = datetime.strptime(str(location_line[0].strip()) + str(location_line[1].strip()), "%Y%m%d%H%M")
            Status = location_line[3].strip()
            Latitude = float(lat_lon_to_float(location_line[4].strip()))
            Longitude = float(lat_lon_to_float(location_line[5].strip()))
            Max_wind = float(location_line[6].strip())
            Minimum_pressure = float(location_line[7].strip())
            Low_Wind_NE = float(location_line[8].strip())
            Low_Wind_SE = float(location_line[9].strip())
            Low_Wind_SW = float(location_line[10].strip())
            Low_Wind_NW = float(location_line[11].strip())
            LModerate_Wind_NE = float(location_line[12].strip())
            LModerate_Wind_SE = float(location_line[13].strip())
            LModerate_Wind_SW = float(location_line[14].strip())
            LModerate_Wind_NW = float(location_line[15].strip())
            High_Wind_NE = float(location_line[16].strip())
            High_Wind_SE = float(location_line[17].strip())
            High_Wind_SW = float(location_line[18].strip())
            High_Wind_NW = float(location_line[19].strip())
            Radius_Of_Max_Wind = float(location_line[20].strip())

            data.append([storm_number, Name, Date,Time,Date_Time, Status, Latitude, Longitude, Max_wind, Minimum_pressure, Low_Wind_NE, Low_Wind_SE, Low_Wind_SW, Low_Wind_NW,
                        LModerate_Wind_NE, LModerate_Wind_SE, LModerate_Wind_SW, LModerate_Wind_NW, High_Wind_NE, High_Wind_SE, High_Wind_SW, High_Wind_NW, Radius_Of_Max_Wind])

### Data Frame

In [4]:
colums = ['ID', 'Name', 'Date', 'Time',"Date_Time", 'Status', 'Latitude',
       'Longitude', 'Max_wind', 'Minimum_pressure', 'Low_Wind_NE',
       'Low_Wind_SE', 'Low_Wind_SW', 'Low_Wind_NW', 'Moderate_Wind_NE',
       'Moderate_Wind_SE', 'Moderate_Wind_SW', 'Moderate_Wind_NW',
       'High_Wind_NE', 'High_Wind_SE', 'High_Wind_SW', 'High_Wind_NW', "Radius_Of_Max_Wind"]
df_raw = pd.DataFrame(data, columns=colums)
df_raw

,ID,Name,Date,Time,Date_Time,Status,Latitude,Longitude,Max_wind,Minimum_pressure,...,Low_Wind_NW,Moderate_Wind_NE,Moderate_Wind_SE,Moderate_Wind_SW,Moderate_Wind_NW,High_Wind_NE,High_Wind_SE,High_Wind_SW,High_Wind_NW,Radius_Of_Max_Wind
0,AL011851,UNNAMED,18510625,0000,1851-06-25 00:00:00,HU,28.0,-94.8,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
1,AL011851,UNNAMED,18510625,0600,1851-06-25 06:00:00,HU,28.0,-95.4,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
2,AL011851,UNNAMED,18510625,1200,1851-06-25 12:00:00,HU,28.0,-96.0,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
3,AL011851,UNNAMED,18510625,1800,1851-06-25 18:00:00,HU,28.1,-96.5,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
4,AL011851,UNNAMED,18510625,2100,1851-06-25 21:00:00,HU,28.2,-96.8,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53496,AL212021,WANDA,20211107,0000,2021-11-07 00:00:00,TS,37.4,-37.4,35.0,1003.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0
53497,AL212021,WANDA,20211107,0600,2021-11-07 06:00:00,TS,38.1,-36.4,35.0,1004.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45.0
53498,AL212021,WANDA,20211107,1200,2021-11-07 12:00:00,LO,39.2,-34.9,35.0,1006.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0
53499,AL212021,WANDA,20211107,1800,2021-11-07 18:00:00,LO,40.9,-32.8,40.0,1006.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0
53500,AL212021,WANDA,20211108,0000,2021-11-08 00:00:00,LO,43.2,-29.7,40.0,1006.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0

### Export as csv

In [5]:
df_raw.to_csv("../Process_data/Hu_1851_2021.csv")